apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app : nginx-app
  template:
    metadata:
      labels:
        app : nginx-app

   spec:
      containers:
        - name: nginx-app
          image: archanaadmin02/my_nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
